/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthLayoutRouteImport } from './routes/_auth-layout'
import { Route as AuthLayoutIndexRouteImport } from './routes/_auth-layout/index'
import { Route as AuthLayoutUsersRouteImport } from './routes/_auth-layout/users'
import { Route as AuthLayoutSettingsRouteImport } from './routes/_auth-layout/settings'
import { Route as AuthLayoutAnalyticsRouteImport } from './routes/_auth-layout/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutIndexRoute = AuthLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutUsersRoute = AuthLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutSettingsRoute = AuthLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAnalyticsRoute = AuthLayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/analytics': typeof AuthLayoutAnalyticsRoute
  '/settings': typeof AuthLayoutSettingsRoute
  '/users': typeof AuthLayoutUsersRoute
  '/': typeof AuthLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AuthLayoutAnalyticsRoute
  '/settings': typeof AuthLayoutSettingsRoute
  '/users': typeof AuthLayoutUsersRoute
  '/': typeof AuthLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth-layout': typeof AuthLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth-layout/analytics': typeof AuthLayoutAnalyticsRoute
  '/_auth-layout/settings': typeof AuthLayoutSettingsRoute
  '/_auth-layout/users': typeof AuthLayoutUsersRoute
  '/_auth-layout/': typeof AuthLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/analytics' | '/settings' | '/users' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/analytics' | '/settings' | '/users' | '/'
  id:
    | '__root__'
    | '/_auth-layout'
    | '/login'
    | '/_auth-layout/analytics'
    | '/_auth-layout/settings'
    | '/_auth-layout/users'
    | '/_auth-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout/': {
      id: '/_auth-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/users': {
      id: '/_auth-layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthLayoutUsersRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/settings': {
      id: '/_auth-layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthLayoutSettingsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/analytics': {
      id: '/_auth-layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthLayoutAnalyticsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutAnalyticsRoute: typeof AuthLayoutAnalyticsRoute
  AuthLayoutSettingsRoute: typeof AuthLayoutSettingsRoute
  AuthLayoutUsersRoute: typeof AuthLayoutUsersRoute
  AuthLayoutIndexRoute: typeof AuthLayoutIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAnalyticsRoute: AuthLayoutAnalyticsRoute,
  AuthLayoutSettingsRoute: AuthLayoutSettingsRoute,
  AuthLayoutUsersRoute: AuthLayoutUsersRoute,
  AuthLayoutIndexRoute: AuthLayoutIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
